version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # upgrade to 18 to fix package compatibility issues
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build complete

artifacts:
  files:
    - app.js
    - package.json
    - package-lock.json
    - node_modules/**/*  # optional if you deploy with node_modules
    - public/**/*        # if you use a public/ folder
    - routes/**/*        # if you have a routes/ folder
    - views/**/*         # for templating engines
